version: "3.3"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8083:8080"
    volumes:
      - ./api_docs/src/swagger.yml:/usr/share/nginx/html/swagger.yml
    environment:
      URL: swagger.yml

  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./back_end/src:/var/www
      - ./back_end/.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./back_end/.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    volumes:
      - ./back_end/src:/var/www
      - ./back_end/.docker/php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
    build:
      context: ./back_end/.docker/php/
      dockerfile: Dockerfile
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: supersecretpassword
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    
  web:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    volumes:
      - ./front_end:/home/node/app
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=development
    