version: "3.3"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8083:8080"
    volumes:
      - ./api_docs/src/swagger.yml:/usr/share/nginx/html/swagger.yml
    environment:
      URL: swagger.yml

